FROM apache/airflow:2.10.5

RUN pip install apache-airflow-providers-mysql==4.0.0
RUN pip install selenium==4.29.0
RUN pip install mysql-connector-python==9.2.0
RUN pip install pandas==2.2.3
RUN pip install selenium==4.29.0